name: broadcaster
description: A simple state management for flutter
version: 1.0.0
author: Everton Santos <everton.build@gmail.com>
homepage: https://github.com/everton-e26/broadcaster

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  provider: ^4.0.3
  rxdart: ^0.23.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
